### ISSUE TITLE
highlight current grid of clips on mix window

### ISSUE THREAD

**Issue by baovuong** [osakared/apc-key-25-bitwig#2]
Hey,

I was wondering if there is a way to have the controller highlight the current grid on the mix window, like how launchpad and apc mini highlights the current grid. Essentially, based on the position on the clip launcher, it will focus those clips on the mix window, and move the focus if the navigate buttons were activated on the controller. If that makes sense.

**Comment by Lucid-Network** [comment]
was just about to ask this, yea would be good to have the visual feedback on screen.

**Comment by thomasjwebb** [comment]
Added in the latest commit. I kind of don't like how it looks but seems to be the most straightforward way to tell Bitwig to highlight.
