### ISSUE TITLE
Shift stop working

### ISSUE THREAD

**Issue by MushiTheMoshi** [osakared/apc-key-25-bitwig#25]
Hi there,

Great work done here, really appreciate it.

When load at startup layout seems to be in matrix mode instead of launcher mode, if I try to switch to launch mode  shift key is not working.

Any help here will be much appreciate it.

Thanks in advance,
Julio

**Comment by thomasjwebb** [comment]
I'll have time to look at that this weekend

**Comment by thomasjwebb** [comment]
I'm not able to replicate this issue. I tried the latest version of Bitwig and I don't have this issue. It starts out in clip launcher mode and it switches between modes correctly when I do shift+sustain. What version of Bitwig and OS are you using?

Here is a version I built using the latest version of the Bitwig SDK in case that helps. I'm working on a new release that will support the new version of the APC Key 25, which surprisingly doesn't seem to work, despite having the same buttons.

[APCKey25.zip](https://github.com/osakared/apc-key-25-bitwig/files/10474981/APCKey25.zip)

**Comment by MushiTheMoshi** [comment]
Hi 

Sorry, forgot to mention that now is working just fine. I am not sure why it worked though.

 Thank you for your help!

**Comment by thomasjwebb** [comment]
Oh I'm glad to hear then!

**Comment by dracoplasma** [comment]
Hello! I am having the exact same issue. The controller starts in matrix mode, and my shift key just triggers another note. I am not able to switch between modes.

**Comment by thomasjwebb** [comment]
Have you tried the new version that's a plugin instead of script file?

**Comment by thomasjwebb** [comment]
Also, are you using the old or new versions? I haven't released the version that works with the new version yet.

**Comment by thomasjwebb** [comment]
Also, are you using the old version or mk2? This plugin won't work with mk2. An upcoming release will, but I'm not quite done with it yet.

**Comment by dracoplasma** [comment]
Hi, thanks for the reply! That would be the issue then, I am using mk2. I tried the bwextension in the github repo.
