### ISSUE TITLE
support for scene launching on groups?

### ISSUE THREAD

**Issue by mark-schulze** [osakared/apc-key-25-bitwig#3]
Hey,

it seems that group tracks are ignored by the script, any chance to have the scene launching on groups working?

**Comment by skysplitterink** [comment]
Also it would be amazing if the groups would close and open on APC like they do in Ableton.

**Comment by thomasjwebb** [comment]
With the latest commit I changed it so it shows a group track as one track, but if you enter the group it shows the individual tracks in the group
