### ISSUE TITLE
Remote color coding and naming broken

### ISSUE THREAD

**Issue by MatjoeP** [osakared/apc-key-25-bitwig#9]
I notice now with v 3 that the remote section does not get the usual colors. Neither do the control names get displayed at the bottom. Instead the text "common" gets displayed.

**Comment by MatjoeP** [comment]
Thanks!

Mathieu Pé

www.orbitproduction.studio

**Comment by thomasjwebb** [comment]
Okay I'm not sure what you mean by this I didn't see any issues on the remote page. It might help if you added a screenshot. But also I just updated the api version to 2 so who knows maybe that will fix it anyway.

**Comment by MatjoeP** [comment]
![Remotes](https://user-images.githubusercontent.com/28061181/66269276-fd81ae80-e846-11e9-87ae-49c132239cad.jpeg)

This is how it is supposed to look like ( colors next to the remotes  and parameters listed dynamically at the bottom of the screen )

Now here is what it looks like when using the APC-Key-25 to control the exact same device. 

![Remotes APC-Key-25](https://user-images.githubusercontent.com/28061181/66269339-96b0c500-e847-11e9-8de5-f8b90537a647.jpeg)

**Comment by thomasjwebb** [comment]
Fixed in separate branch (`grig.controller`) I'll close this after that's merged into main.

**Comment by thomasjwebb** [comment]
Fixed in [latest release](https://github.com/osakared/apc-key-25-bitwig/releases/tag/1.3).
